### ISSUE TITLE
Plugin requiring license on IDEA Ultimate Edition

### ISSUE THREAD

**Issue by Frontear** [manifold-systems/manifold#119]
I was recently informed that the Manifold plugin is actually free in 2 cases (one of which doesn't seem to be implemented by JetBrains):
- If you have a student/faculty (basically an education) license
- If you have IDEA Community Edition

I personally use IDEA Ultimate Edition, because I have an education license, so why not? However, when I installed the Manifold plugin, it asks me for a license activation. This surprised me, because there are no mentions of it requiring payment (normally this would not be an issue, but as a student, money.. isn't a friend).

I decided to download community edition, and viola, but it actually works. It does not require any license. I'm curious as to why this is the case. Is this an issue from JetBrains, or is there a bigger problem here?

It wouldn't necessarily be difficult to transfer workspaces, I could probably run two installations and have them work on separate projects, but that's quite an inconvenience. With all that being said, is there a way to get Manifold running on an ultimate edition installation, or will I have to downgrade to community edition?

**Comment by rsmckinney** [comment]
Hi Ali.  Manifold is free for IJ Community Edition because it is our
mission to keep Manifold free for projects using open source software.
Manifold also supports the full spectrum of JetBrains license deals,
including those concerning education, however the Marketplace is at this
time incomplete with respect licensing structure.  For instance, as you
have discovered student licenses are not yet available for plugins.
However, JetBrains is working diligently toward completing Marketplace,
keep a lookout!

Thanks for you interest in Manifold!

Scott

**Comment by Frontear** [comment]
Thank you, you've cleared up the issue. I only now hope that JetBrains complete's the marketplace functionality soon.
