### ISSUE TITLE
how to get the actual  subtype(Class)  in static extension method 

### ISSUE THREAD

**Issue by wxq1990** [manifold-systems/manifold#122]
if i write a static extension method for Object,
and in the method i want to get the actual Class object,
what should i do?

![GQS~H 03{C ~DYHB3LNJ~O0](https://user-images.githubusercontent.com/10300594/65501930-6e929f00-def4-11e9-97f4-c7cf73e30f4e.png)

**Comment by rsmckinney** [comment]
@wxq1990.  Static methods in Java do not have access to static context. For instance, there is no way to know the calling class from within a static method.  However, in your case since you are essentially targeting the `Class` type, why not add an instance extension method on `Class`? 
```java
@Extension
public class MyClassExtension {
  public static BaseDao dao(@This Class thiz) {
    return Contexts.DAOS.get(getTypeName());
  }
}
```
Then you can use it like this:
```java
User.class.dao();
```

**Comment by wxq1990** [comment]
i see thanks
