### ISSUE TITLE
Manifold and intellij

### ISSUE THREAD

**Issue by zacharywhitley** [manifold-systems/manifold#123]
This looks like a really exciting project and thank you for creating it. I have one question and one bit of feedback. First the feedback. It would be nice to mention on the Github page and/or website that intellij is a paid plugin. I'm a bit proponent of programmers getting paid so I'm all for it but it would have been nice to have known that up front. It's a bit like in-app purchases. You see this awesome project, think, "I'm checking this out." and you get excited. You go to install the plugin and find out you have to pay for it. Like I said I have noooooo problem with that. It just would have been nice to know upfront.

My question is, can you develop with Manifold reasonably without the plugin. ie. If I'm on a team and decide to use Manifold does that require that I get the entire team to buy into using Manifold and buying intellij plugin licenses for everyone?

**Comment by rsmckinney** [comment]
@zacharywhitley.  Hi.  Thanks for the feedback and good questions.  

- The plugin is free with IntelliJ IDEA Community Edition and is paid with IDEA Ultimate.  Generally using Manifold is free with when developing open source projects; IDEA Ultimate is not open source.  I'll make this clearer in the docs.
- Reasonably?  Depends on how deeply you drink of Manifold.  You can always use Manifold without the plugin, it comes down to your tolerance for false error highlighting in IJ. Perhaps more importantly many of the benefits of Manifold are lost without the plugin -- static typing/analysis/tooling is the bread manifold butters.

Cheers!

**Comment by zacharywhitley** [comment]
That's fantastic. I'd definitely update that on the docs. I happen to run IntelliJ IDEA Ultimate so I just naturally tried to install it and was sad :( but I'd be happy to install Community as well if I can use Manifold. I'd really like to give a try using Manifold for RDF data. There's a ton of boilerplate code just mapping an ontology/vocabulary into Java and then you have to keep them up to date with changes. It would be awesome if you could just point to an rdf file and get your mappings. Same thing goes for the api's where there is a lot of duplication with native api's. There are Literal type that are just strings with a language tag or datatype tag. It would be really nice if you could just extend Strings to include that.

Thanks again. I'm really excited to see what I can do with Manifold!

**Comment by rsmckinney** [comment]
Go for it! That's what Type Manifolds are all about.

A while back while developing the core manifold framework I wrote a type manifold for DBpedia as a proof of concept wrt remote, open-ended resources. This turned out to be an RDF manifold where one Java interface maps to one ontology class. The interface reflects the rdfs:subClassOf relationship using Java interface inheritance. Each property on the interface exists as a "getter" method returning either another interface, a primitive, a String or other Java class based on the defined schema type. I got far enough for the POC, but didn't bother taking it beyond research.

**Comment by Proximyst** [comment]
I'd say it's a rather interesting argument that you're not allowing it to be used for free on non-open-source projects, while, as far as I see, the IntelliJ plugin is also not open-source. Is there a reason for this? I'd enjoy hacking it up to get it to work with IJ Ultimate on my student licence for FOSS work.

**Comment by rsmckinney** [comment]
@Proximyst Hi. Until recently the plugin project _was_ open source until it became an optional paid plugin via the new JetBrains Marketplace.  The truth of the matter is the paid plugin keeps Manifold alive; without compensation the project will simply go dormant -- ongoing development entails a lot of time and knowledge. 

In the meantime why not simply use Community Edition for your FOSS work?  If there are features in Ultimate you need, following the Marketplace license terms, you would have to purchase the plugin anyway, which is the whole idea -- if you use Ultimate, you pay, otherwise it's free.

Now if you're using Ultimate as a student, that discount also applies to the Manifold plugin.  The problem right now is the JetBrains Marketplace is still under development and they have not yet finished extending the licensing discounts to plugins.
