### ISSUE TITLE
Implement primitive type aliases

### ISSUE THREAD

**Issue by drekbour** [manifold-systems/manifold#133]
**Is your feature request related to a problem? Please describe.**
https://stackoverflow.com/questions/58622163/most-performant-way-to-achieve-type-safety-on-primitive-types-in-java

**Describe the solution you'd like**
Type-safe aliasing of Java primitives. e.g.

    alias celcius, kelvin as double;
    public boolean isSafeForHuman(celcius temperature); 

**Describe alternatives you've considered**
`@Structural` allows aliases on interfaces
In Scala, this is `type celcius = double` and goes beyond primitives to allow `type RuleBook = Set[Rule]`

**Comment by rsmckinney** [comment]
I understand the sentiment regarding performance, however aliasing is essentially a form of macro substitution, which I personally don't like very much because my experience with it in C/C++ is unpleasant. Generally the feature tends to confuse much more than it clarifies. In other words the relatively rare cases where the performance impact of wrapping/unwrapping a primitive value has significance are not enough to justify aliasing as a language feature. In my view, I'd go the other way -- use the `Temperature` class from the [manifold-science](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-science) framework to provide guarantees around units of measure and type-safety. If a profiler exposes a hotspot involving data access in Temperature, and if that matters, only then consider altering code to address performance around that. You know what they say about premature optimization ;)

In any case if you have a specific use-case, I'd be interested to hear more about it.  Maybe there's something I haven't considered or don't fully understand.

**Comment by drekbour** [comment]
I have no specific usecases, just the general opinion that aliases "feel ok" to me (so long as they are used rationally...). I've been looking at Kotlin and that also has a `typealias` keyword but I suspect for every language that admits this feature in there's one that doesn't :)

If this doesn't sit well with you, please close.

> where the performance impact of wrapping/unwrapping a primitive value has significance
You downplay one of the very worst aspects of Java!

**Comment by rsmckinney** [comment]
>You downplay one of the very worst aspects of Java!

Heheh. Sigh, I know. Re wrapping/boxing, it's ugly.  [Value types](https://jaxenter.com/java-value-type-163446.html) fixes this and may provide an alternative solution for your `celcius` example.

> (so long as they are used rationally...)

Exactly.  For instance, generated classes can get pretty unwieldy with nesting and naming; type aliases would be nice there. But my C++ PTSD kicks in whenever I consider the idea. The rampant abuse of aliasing via macro substitution, in my experience, clearly demonstrates they tend not be used rationally, at all.

I'll leave this open for a while anyway in case others share your view. I could be persuaded.
