### ISSUE TITLE
[Feature request] yield and async/await functionality as in javascript

### ISSUE THREAD

**Issue by WilliamStone** [manifold-systems/manifold#147]
Hi, 

Manifold has become very powerful, and opens so many possibilities. So I wonder if it can be further extended to resolve a long inconvenience.
With microservice etc., RPC is more and more used and asynchronous invocation has became mandatory. There's no excellent solution regarding as asynchronous method invocation in Java. JavaScript's async/await mechanism seems better than all counterparts in Java. So if we can implement async/await in Java it would be of great convenience in asynchronous programming. 
And yield/generator is also very useful in certain scenarios and yield seems can be implemented in similar way as async/await, so it would be ideal if both are implemented at once. Please consider the proposal and many thanks!

**Comment by rsmckinney** [comment]
@WilliamStone Hi. I hear you, although to implement async efficiently we need platform independent _fibers_ -- the means to suspend execution state within a thread and transfer to other frames of execution, back and forth, quickly. As it turns out the JVM is adding fibers to an up-comping release via project [Loom](https://cr.openjdk.java.net/~rpressler/loom/Loom-Proposal.html).  I haven't been following it, but I assume async/await will be part of this release.
