### ISSUE TITLE
IntelliJ support custom Type Manifolds

### ISSUE THREAD

**Issue by cyroxis** [manifold-systems/manifold#178]
Hi, I have been attempting to generate classes using a custom type manifold. I have placed the TypeManifold in a separate maven module with a dependency as seemed to be indicated by [issue 158](https://github.com/manifold-systems/manifold/issues/158). This got the code generation working but I am having issues that seem to be related.

1. IJ is only able to run the project after `mvn compile` is ran from the command line. Otherwise I get the following error in IJ
```
Error:(16, 9) java: cannot find symbol
  symbol:   class RunnerWinner
  location: class com.mt.Runner
```

2. Even after successfully running the application IJ does not recognize the generated symbols 
![image](https://user-images.githubusercontent.com/1709029/81604150-7462c500-939d-11ea-872b-e45925a8dbec.png)

[Sample Project](https://github.com/cyroxis/manifold_test)
IntelliJ 2020.1.1 CE
Manifold Plugin 2020.1.9

**Comment by rsmckinney** [comment]
@cyroxis Hi. Even though you have separate module dependencies, which is good, the IntelliJ plugin can't apply a type manifold project to itself. Essentially, the plugin can only apply a type manifold that is a _binary_ dependency of a project. As a consequence, you need to extract your sample module "consume" as a separate project with a dependency on your type manifold.

Make sense?

**Comment by cyroxis** [comment]
That does make sense and I was able to test it by generating a .jar of the generate module and using that as the dependency in IJ. 

That greatly complicates my use case. I was wanting to generate has a lot of domain dependencies that would be difficult to abstract out of the main project. Looks like I will have to either create some sort of template language (like mantl for Java files) or use a different solution to generate the code. 

Thank you for your help

**Comment by rsmckinney** [comment]
@cyroxis Ah, I see.  I wonder if you could keep your type manifold local by adding an additional _runtime_ dependency of a binary version of your project to itself? It's a hack, but it would let IJ see your type manifold.

**Comment by cyroxis** [comment]
Hmm interesting I will explore that avenue.

What I have been working on is creating a generic interface

**Comment by cyroxis** [comment]
Thanks @rsmckinney I will look into that more, it does sound hackey.

**Comment by cyroxis** [comment]
Thanks @rsmckinney I will look into that to see if it helps.

What I have been currently working on is loading a type generator from the consuming project.

```
// Manifold Project
public interface TypeCreator {
  String getTypeName(String fqn);
  SrcClass generateClass(String fqn, Class<?> sourceType);
}
public @interface TemplateWith {
  Class<? extends TypeCreator> value();
}

// Using Project
@TemplateWith(Bar.class)
public class Foo {
  //...
}
public class BarCreator implements TypeCreator {
  public String getTypeName(String fqn) { return fqn + "Bar");
  //...
}
```

I am able to dynamically load the `TypeCreator` from source and execute it as long as I hard code the `FooBar` type in my `ITypeManifold`. What I am trying to solve now is reliably parsing the fully qualified name of the template (e.g `BarCreator`). 

The issue with that is using the tools Manifold provides to dynamically load the annotated class (e.g. `Foo`) creates a recursive call back to my manifold since the lazy loading in `JavaTypeManifold` is not yet complete.

Is there a way to implement `ITypeManifold` to avoid that recursion since I know that I am not modifying the annotated class (e.g. `Foo`)?

If not I will have to look using different tools to parse the annotation from the file.

**Comment by rsmckinney** [comment]
@cyroxis can you privately share this project via github or similar?

**Comment by cyroxis** [comment]
The code is available in [manifold_test](https://github.com/cyroxis/manifold_test).

The current version loads 'Bar.java' but because there is still a recursive call to the loading (that is handled by `TypeTemplateManifold.java:110`) the type name is not correctly registered.

If you comment out `TypeTemplateManifold.java:110` it results in a stack overflow when loading `Bar.java`
If generated type name is hard coded in then `InMemoryClassLoader` will load `WinnerMaker.java` and generate the class

**Comment by rsmckinney** [comment]
@cyroxis Ok, I'll carve out a bit of time for this tomorrow. Thanks for supplying the project on github!

**Comment by rsmckinney** [comment]
@cyroxis  Ok I've had a decent look at your project. What I gather is, using the @TemplateWith annotation you declare a Java "template" class and, via the annotation's class argument, the "maker" dynamically produces a new type having a name consisting of the template's class name and whatever the maker chooses as a suffix.

First, to use the scheme as you have it, you should also break out the "maker" classes into a separate module and have the consumer module depend on that. This way you can make new instances of a maker because it will have been compiled through the dependency. Additionally, you should parse the text of the template classes instead of compiling them to find and use the annotation. But, honestly, this is getting complicated and will get more complicated as newer problems arise.

Perhaps a better approach is to look at the [DarkJ](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-darkj) manifold and follow its example. For instance, the template classes could be Java _resources_ having their own special file extension. Similar to the darkj manifold, yours can create a Java class utilizing the maker classes.

Just my thoughts.
