### ISSUE TITLE
Can I disable the string template by default?

### ISSUE THREAD

**Issue by moonfruit** [manifold-systems/manifold#179]
As the title, can I disable the string template by default?
Because I want to use manifold in an existing project, and I only use it in new code. So I don't want to affect the legacy codes.

**Comment by rsmckinney** [comment]
@moonfruit Hi. Which manifold dependencies are you using? If you're using `manifold-all`, which is a "Fat" Jar, instead you'll need to select only the dependencies you need. For instance, if you are using manifold for GraphQL, use the `manifold-graphql` dependency. It transitively exposes your project to `manifold-strings`, but you can exclude it from the dependency. In particular, if you are using Maven:
```xml
        <dependency>
            <groupId>systems.manifold</groupId>
            <artifactId>manifold-graphql</artifactId>
            <version>${manifold.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>systems.manifold</groupId>
                    <artifactId>manifold.strings</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Similarly, with Gradle use `exclude`:
```groovy
exclude group: 'system.manifold', module: 'manifold-strings'
```
In any case I am probably going to make manifold modules declare dependencies on `manifold-strings` as "optional" in Maven terms, which hides it from dependent modules. But for now you should still try excluding it in your project.

Make sense?

**Comment by rsmckinney** [comment]
*Update*

In the meantime, I forgot about [ITemplateProcessorGate](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-strings/src/main/java/manifold/strings/api/ITemplateProcessorGate.java).  You can implement this service to block string template processing by type name. You basically implement the `exclude` method and return true/false to allow the specified to compile with string template processing. Let me know if you need help with it.

Again, I am changing manifold's modules so that you won't have to do this; you'll have to opt in for  string templates.  But you can go ahead with ITemplateProcessorGate if you can't wait for the next Manifold release, probably a day.

**Comment by moonfruit** [comment]
Thank @rsmckinney very much, this is exactly what I need.
And I am very interested in the new version, looking forward to its release.
