### ISSUE TITLE
[Feature] Type Aliases

### ISSUE THREAD

**Issue by andob** [manifold-systems/manifold#202]
What about syntactic sugar type aliases? The plugin will recognise the alias names, but at compile time, they will be replaced with the aliased type. For instance:

```java
@TypeAlias(Long.class)
public class Timestamp {}

@TypeAlias(long.class)
public class timestamp {}
```

```java
public class Invoice
{
    public String name;
    public Timestamp dueDate; //nullable variable, can be null or something
    public timestamp createdAt; //nonnullable variable, will always be something
    public timestamp modifiedAt; //nonnullable
}
```

This will compile to:

```java
public class Invoice
{
    public String name;
    public Long dueDate;
    public long createdAt;
    public long modifiedAt;
}
```

It would also be nice if we could write extension methods over type aliases, for instance:

```java
@Extension
public class TimestampExtensions
{
    public static TimestampFormatter format(@This @NotNull timestamp timestamp)
    {
        return new TimestampFormatter(timestamp);
    }
}
```

```java
Invoice invoice=new Invoice();
invoice.name="some invoice";
invoice.createdAt=now();

System.out.println(invoice.createdAt.format().date());
```

At runtime, these extensions will be applied to the long primitive. But it would be nice if the plugin will prevent us from doing this:

```java
new Long(1234L).format().date(); //does not compile
((timestamp)1234L).format().date(); //does compile
```

**A little bit of context and back story**

There is this antipattern called "primitive type obsession". I recommend [this video](https://www.youtube.com/watch?v=t3DBzaeid74). Basically, it's better to use objects than primitives (ID class instead of int, DateTime/Timestamp/whatever instead of long, EmailAddress/PhoneNumber/etc instead of String). I have a Java project in which I used only longs to represent date/times. When I tried to apply this concept here, it doesn't seemed to get any better, than, say, applying the same concept in a kotlin-only project (which I already did). In Java, the code would just become more boilerplateish, because:

1. Primitives have natural operators. Defining such wrapper type in kotlin would be easy because we have operator overloading in kotlin
2. In Java it is easy to use long to represent only non-nullable objects, and Long to represent nullable objects. Using a wrapper class would prevent us from doing that distinction. In kotlin this would also be fine, because declaring a variable of type :T means it is nonnullable, and :T? means it is nullable.

I think this feature would be great because it could bring zero-cost powerful abstractions.

It could also be overused and abused, but, of course, this is true for any language feature Java language developers refused to implement.

**Comment by rsmckinney** [comment]
@andob Hi Andrei.  

Nice suggestions here!  I see at least few different ideas intermingled, notably Type Aliases, Operator Overloading, and Type-safe Units (and perhaps nullable value types).  It's all good!

Regarding your Timestamp/timestamp example, I think most of that could be achieved using Manifold's [Operator Overloading](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#operator-overloading) and [Type-safe Units](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#unit-expressions) support. Have you ventured into that corner of Manifold? For instance, would the [Time](https://github.com/manifold-systems/manifold/blob/d71f1268400290a321451426800a3363a0f7afdc/manifold-deps-parent/manifold-science/src/main/java/manifold/science/measures/Time.java) type suffice?

Btw, excellent talk re The Power of Types (Danny Preussler). As you may have surmised, I'm an ardent supporter of static typing in the spirit of Preussler's talk. The essence of his talk, which I'll take the liberty to reduce to "If you can use the compiler to verify what must otherwise exist as tests, do it." is a guiding principle behind Manifold.  The notion of type-safe units and type manifolds go beyond his talk, but I would like to think Danny would appreciate those ideas.
