### ISSUE TITLE
[Q] What is IBootstrap.dasBoot() and why it is compiled into every single class?

### ISSUE THREAD

**Issue by andob** [manifold-systems/manifold#203]
I am using extension methods module and I was curious about how things get compiled. So this:

```java
String someString="test test test".withCapitalizedFirstLetter();
```

Gives me this decompiled code:

```java
String point = StringExtensions.withCapitalizedFirstLetter("test test test");
```

But there is this static initialization block..

```java
static {
        IBootstrap.dasBoot();
    }
```

..inside every single compiled class. Even the ones that don't use extension methods at all. I understand that this is initializing some kind of bootstrap regarding manifold modules. But I only use the extensions module. And earlier I saw that at compile time, extension methods are just replaced with the corresponding static method from the extensions package.

Is this initialization critical when using only the extensions module?

If the extensions module could be used without it, is there some kind of gradle configration flag that I can set so that this block will not be inserted into any class?

If not, it would be possible or recommended to develop such feature?

**Comment by rsmckinney** [comment]
@andob In the context of extensions `dasBoot()` is injected into classes to ensure:

1. Disable the Java 9 warning "An illegal reflective access operation has occurred", because that message is in my view unnecessarily alarming. This is a noop when running on Java 8 / Android.
2. To dynamically open the java.base module to the manifold module for reflection access, which is a noop running on Java 8 / Android.

Note `dasBoot()` performs these tasks one time, subsequent calls simply return i.e., there is no performance penalty.

If you know your code will never run on Java 9+ and/or you don't mind the Java 9+ warning message, you can eliminate the `dasBoot()` static initializer via the `no-bootstrap` plugin argument:

```
-Xplugin:Manifold no-bootstrap
```

**Comment by andob** [comment]
ok, cool. I added the flag. Indeed, the static initialization block is gone.

I think there should be a documentation page with all Manifold compiler plugin flags :)

**Comment by rsmckinney** [comment]
I'll be darned, you're right, the `no-bootstrap` option isn't documented. I just added some docs for that with change https://github.com/manifold-systems/manifold/commit/c50f95c42cdb075ea590d54ebee617f73b33b1da.  But I do like the idea of improving manifold docs so that this info is maybe easier to find.
