### ISSUE TITLE
Is it possible to reference compiled Manifold templates without the IntelliJ plugin?

### ISSUE THREAD

**Issue by mtdowling** [manifold-systems/manifold#210]
I'm testing the use of Manifold templates in IntelliJ _without_ the Manifold IntelliJ plugin. After defining a template, and running Gradle `build` successfully from the command line, IntelliJ is saying that it "Cannot resolve symbol 'Hello'"). I see the generated class file in `build/classes/java/...`, but I guess it doesn't work because there's no source file placed in `generated/sources/annotationProcessor/java/main/...`?

If I start using Manifold templates in production, I'll buy the plugin, but I want to see if I can at least get IntelliJ to be able to reference compiled templates. In open source projects that use Manifold Templates, there are probably use cases where developers need to make changes to a project, they don't need to edit templates, and all they really want is IntelliJ to not tell them the code is broken.

Maybe I'm missing some IntelliJ setting that would make this work?

**Comment by rsmckinney** [comment]
@mtdowling First, be sure you Gradle build copies `.mtl` template resource files to your target directory. The content of the template file is not compiled into the template class, instead the template class references *offsets* into the template file. Using offsets ensures very large template files do not exceed the Java 64k method limit. Second, Manifold never generates source files, not in generated/sources/annotationProcessor/java/main/, not anywhere -- it's not an annotation processor, which is a good thing :)  Third, regarding the error message, "Cannot resolve symbol 'Hello'", what is `Hello`? Is that at template file? Thanks.

**Comment by mtdowling** [comment]
Yeah, ‘Hello’ is the name of a template I’m referencing. To be clear, everything works when I run Gradle from the command line; it’s all wired up correctly, it compiles, symbols are resolved, templates can be loaded, etc. The only issue I’m having is getting IntelliJ to be able to know about the code generated from the templates.

**Comment by rsmckinney** [comment]
It should work, so this sounds like a bug. I'll try to repro. Thanks.

**Comment by rsmckinney** [comment]
Ok, I think I understand your use-case now. Given file `foo/MyTemplate.html.mtl` you want to reference the corresponding type `foo.MyTemplate` in source file `foo/Main.java` in the same project inside IntelliJ IDEA, but without using the Manifold IntelliJ plugin. Right?

Well, if `Main.java` and `MyTemplate.html.mtl` are in the same project, this is not possible since IntelliJ must make *source-level* sense of `MyTemplate.html.mtl`, which it cannot do without the assistance of the Manifold plugin, otherwise `foo/MyTemplate.html.mtl` is just a file in the context of the IntelliJ java editor. As you point out, however, the project still compiles etc. because your project uses the `manifold-template` and `manifold-template-rt` dependencies. So this is  "just" a matter of the IJ editor not recognizing the types.

Now, if you require that other developers access your templates from within IJ editors but without the Manifold plugin, you might consider breaking the templates out into a separate dependency. This way references to them are never at the source-level, but are instead at the target level, from .class files. This scenario does not require the plugin since the templates are already compiled. 

Make sense?

**Comment by mtdowling** [comment]
That makes sense. It's unfortunate since it complicates how projects are organized. But thanks for taking a look!

**Comment by rsmckinney** [comment]
@mtdowling No problem. Also, just a reminder, if the issue is cost and if the other devs are using IJ Community Edition, it's all free.

**Comment by mtdowling** [comment]
It looks like the templates implementation builds up Java source code, but I guess it just doesn't write it to disk? Could that be an optional feature flag -- i.e., write the sources to disk in addition to generating the .class files? If this were possible, then I'd get basically my desired outcome: collaborators could contribute to a project using MTL, but wouldn't be required to have the plugin installed. The main drawback would be that someone that doesn't have the Manifold IntelliJ plugin installed would need to compile the project first before IntelliJ would consider code that references compiled templates valid (since the sources wouldn't have been generated yet).

**Comment by rsmckinney** [comment]
Probably better if your mtl usage could be decoupled for a cleaner binary dependency, but if other areas of your architecture make that split too difficult, I could perhaps build a small IJ plugin that provides the mtl functionality you need.

As an aside, I am pondering making the IJ plugin less commercial for IJ Ultimate users. Basically, it'll be free after the trial period, but probably nag a little bit at IJ startup, "Your trial period is over, blah blah blah."

**Comment by mtdowling** [comment]
You’re probably right about separating the projects, it just means stuff like code generators probably need like a 3 package layout (e.g., one for shared code, one for templates that uses shared code, and one to actually use the templates).

As for the IntelliJ plugins, I wouldn’t want you to lose a revenue stream. I also wouldn’t want you to have to maintain a separate plugin if it’s a lot of work or maintenance... if you’re already considering this, what about something like making templates free as part of the plugin for Pro users, and other manifold features aren’t available after the trial period (with the option to “not show again” for people just using templates)? Free with a periodic nag works too.

**Comment by rsmckinney** [comment]
@mtdowling The latest IJ plugin release is free with Ultimate after the trial period, but nags on project load.
