### ISSUE TITLE
Versions past 2021.1.27

### ISSUE THREAD

**Issue by djchapm** [manifold-systems/manifold#315]
Hey - 
Any updates we need to know about past 2021.1.27?  I checked for release notes etc.... When I upgrade I'm seeing compile issues related to package includes.  i.e. from Intellij (using 2021.1.30 manifold plugin), I see the error:

`java: Validation error of type FieldUndefined: GraphQL field 'match' is not defined in the type 'Query' from scope '_default_scope'`

Same for remaining versions 29 and 30.  27 and previous work fine.

The type it's referring to is declared in another gql file in the same directory.

Thanks,
  Dan C.

**Comment by rsmckinney** [comment]
Starting with release 2021.1.28 manifold-graphql provides support for [multiple schemas](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-graphql#configuring-for-multiple-schemas).  That error is indicative of your project having multiple graphql schemas present, but not defining .graphqlconfig files to support that.  In this case the error is saying it can't find the  'match' field because it is looking in the wrong schema. It is likely this error was going undetected in releases prior to 2021.1.28. Please let me know if I can provide further assistance.

Sorry about the lack of release notes on the release tags, change notes are available in the IJ plugin releases.

**Comment by rsmckinney** [comment]
@djchapm have you resolved this issue? Or is there still a problem?

**Comment by djchapm** [comment]
Yep - your link covers it - we have yet to update but created ticket for it.  Thanks!
