### ISSUE TITLE
Why is the IntelliJ plugin payed/can it be made open source?

### ISSUE THREAD

**Issue by Gaming32** [manifold-systems/manifold#342]
I'm curious about the IntelliJ plugin being made open source. I'm curious because I'm interested in (maybe) porting it to other IDE(s) (such as Visual Studio Code and Eclipse, #142). I'm also curious as to why the IntelliJ plugin is payed.

**Comment by rsmckinney** [comment]
Hi @Gaming32. 

Shhhh.  The plugin isn't really paid. You can grab the 30-day free trial from JetBrains Marketplace and continue using it for free indefinitely after the trial ends. I'm pretty much using the Marketplace as a quasi donation platform.
 
The plugin is paid as a means of funding Manifold development. It is the only source of revenue and without it there would be no Manifold.  As it is there's arguably not nearly enough $$ to keep this going, unless minimum wage c. 1980 is acceptable compensation.

Now, this doesn't mean the plugin has to be proprietary. I've been pondering open sourcing it because: 1. I generally  prefer source to be available for others to contribute, debug, etc., and 2. I don't do much to deter reverse engineering anyway, so what's the point? So, maybe it's time. It's a simple matter of flipping the github private/public switch and adding some legalese. I'll ponder some more.

As for "porting" it to VS Code / Eclipse, if it could have been, it would have been. The truth is the IntelliJ platform APIs are vastly different from and vastly more capable than either of Eclipse JDT or LSP. Not that a Manifold plugin couldn't be implemented for those platforms, it's possible, but it would be a completely different animal and probably not as functional. I would love to be shown how wrong I am... another reason to open source the plugin.

I hope I've answered your questions.

Cheers.

**Comment by dnedrow** [comment]
Hi, @rsmckinney ,

The plugin doesn't currently work in the newest versions of IntelliJ/IDEA.

It looks like there may have been changes in the JetBrains Plugin SDK.

If you don't have time, I would like to take a shot at updating it. Consider it a donation. ;)

If you're interested, I'd need repo access.

-David

**Comment by migroskub** [comment]
@rsmckinney I think that there are some major upsides for being fully open-sourced that I'm not sure you've thought about. Notice how great of a library you've been created, and notice how low is your contributors number and actual users amount (the library is pretty unknown, even though it has some mind-blowing features for the Java ecosystem). And to me, the reason is very clear - a person can not (at least from what the documentation says) use this library for more than a month without paying! Check out how others libraries did this - you can be fully open-source, gather much more users, and link donating options in the readme & docs. Github supports this very well. Check the https://github.com/vuejs/vue project for a great example of a sponsor-based real open source project. I personally was very sad to find out this project wasn't really open source, since I and my team at work really liked the features and had plans of using it a lot, until we've found out of the plugin's price, and the boss didn't let this happen (many workplaces decline immediate usage of projects that aren't open source).

I think this project has the potential of being one of the greatest tools that the Java ecosystem has ever seen. But not until the plugin will be open source and people would be able to contribute since right now most of the users won't really count this project as an option (personally I'd also really like to see the code and contribute. but currently I cannot really contribute since it's hard to develop this without seeing the full picture).

**Comment by rsmckinney** [comment]
@dnedrow 
- What isn't working for you? 
- What version are you using? Is it the latest 2022.1 EAP? I'm running that currently and it looks ok on my end.
- I'll likely open the repo in the next couple of days.
Thanks.

**Comment by rsmckinney** [comment]
@migroskub 

I've decided to open the plugin repo, probably within the next couple of days.  Regarding the commercial aspect, I'm aware of donation platforms, perhaps it's time to reconsider that option.        

Thanks for sharing your thoughts here.  

Cheers.

**Comment by rsmckinney** [comment]
The IJ plugin repo is now open/public.

**Comment by migroskub** [comment]
@rsmckinney Thank you!!!
