### ISSUE TITLE
Change graphQL output to deterministic

### ISSUE THREAD

**Issue by grimholtz** [manifold-systems/manifold#381]
The order of array elements appears to be non-deterministic in JSON graphQL output. For example, sometimes I get:

`"tif": { "_in": [0, 99998, 99990, 99999] },`

and othertimes:

`"tif": { "_in": [99990, 99998, 0, 99999] },`

I am guessing that is due to the underlying array/list implementations being used in manifold. Is it possible to use data structures such as `LinkedHashSet` that provide consistent ordering? 

**Is your feature request related to a problem? Please describe.**
This makes unit testing of manifold-generated output extremely difficult because I cannot compare manifold-generated output against known-good output without tests failing. The only alternative is to somehow sort the manifold-generated output before comparison, but sorting arrays that don't have keys is not easy.

**Describe the solution you'd like**
Consistent output of JSON graphql across _N_ runs of the same code.

**Describe alternatives you've considered**
Sorting the JSON graphql string myself. I can provide a full example so you can see complicate this can be (nested arrays, etc). Let me know if you'd like this.

**Comment by rsmckinney** [comment]
Hi @grimholtz.

A list in a graphql response result reflects the order from the json response, the List data structure is always ordered. Perhaps the response data itself is not a List, but is instead a logical Set? If that is the case, your test should ignore order and compare the size and membership of the expected and actual lists. Otherwise, if the raw response form the server is consistent and manifold is somehow reordering the results, I will need a way to reproduce the issue. Thanks.
