### ISSUE TITLE
What is the implementation principle? 

### ISSUE THREAD

**Issue by liudaolunboluo** [manifold-systems/manifold#424]
What is the implementation principle? It doesn't seem like Lombok, which is implemented based on jsr269，I didn't find a similar answer on FAQ

**Comment by rsmckinney** [comment]
Manifold is a Java compiler [plugin](https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html). A plugin hooks into the compiler at an earlier stage than is possible using an annotation processor. Additionally, since the core of manifold is not based on annotations, it made more sense to build it as a plugin. Hope this answers your question.

**Comment by liudaolunboluo** [comment]
> Manifold is a Java compiler [plugin](https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html). A plugin hooks into the compiler at an earlier stage than is possible using an annotation processor. Additionally, since the core of manifold is not based on annotations, it made more sense to build it as a plugin. Hope this answers your question.

So does Manifold also modify the AST syntax tree to modify the code？

**Comment by rsmckinney** [comment]
The manifold project is a collection of subprojects extending from the core. Core manifold, which provides the foundational stuff including "type manifolds", does not modify the AST, however many subprojects do.  These include manifold-ext, manifold-props, manifold-strings, manifold-delegation, etc.
