### ISSUE TITLE
Compilation error: Manifold and Spring have a problem

### ISSUE THREAD

**Issue by po4tamp** [manifold-systems/manifold#44]
**Describe the bug**
After the manifold dependencies in gradle.build have been added to the existing project, 
the project can not be compiled anymore.

**To Reproduce**
1. I have installed the Manifold plugin in IntelliJ and restarted IntelliJ.
2. I've configured the dependencies for Manifold according documentation in existing Gradle project.
In build.gradle:
dependencies {
...
compile group: 'systems.manifold', name: 'manifold-all', version: '0.43-alpha'
compile files("\${System.getProperty('java.home')}/../lib/tools.jar")
}
tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold strings'
    options.fork = true
}
3. For Java compiler, I have configured the following parameter in Intellijs:
-Xplugin:"Manifold dynamic strings"
4. All Spring-Bean classes from the existing project that have an "Value" annotation can no longer be compiled
(i.e. when building with Gradle "build" or compile from IntelliJ).
Here is an example:
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
@Component
public class TestProperties {
       ...
	@Value("${"agent.username}")
    private String username;
	...
}

When compiling the class with Gradle, the following error occurs:
TestProperties.java:95: error: ';' expected
    @Value("${agent.username}")

When compiling the class from IntelliJ, the following error occurs:
Error: java: package agent.username does not exist

**Desktop:**
- OS Type & Version: Microsoft Windows 10 Enterprise, Build 10.0.14393
- Java/JDK version: 1.8.0_144-b01
- IntelliJ IDEA version: IntelliJ IDEA 2018.3.4 (Community Edition), Build #IC-183.5429.30, built on January 29, 2019
- Manifold version: 0.43-alpha
- Manifold IntelliJ plugin version: v0.43-alpha
- Gradle version: 4.1
- Spring boot: 2.0.1.RELEASE
- Spring (core, beans, test etc.): 5.0.5.RELEASE

**Comment by rsmckinney** [comment]
Hi Michael.
`
Manifold supports [string templates](http://manifold.systems/docs.html#templating) where you can embed variables and expressions in a String literal using `$` for variables and `${...}` for expressions, which conflicts with Spring's usage of similar syntax.

You enabled this feature with the `strings` argument in your gradle compilerArgs setting:
```text
2.  options.compilerArgs += '-Xplugin:Manifold strings'
```
and also in the other compiler setting you mentioned:
```text
3. -Xplugin:"Manifold dynamic strings"
```
(you should only need your gradle setting btw)

There are two ways to fix the problem:
1. Remove the `strings` argument:
```text
  options.compilerArgs += '-Xplugin:Manifold'
```
2. Keep using `strings` and improve type-safety. 
For instance, let's say the properties file resource your project uses is in `resources/com/abc/Info.properties`, you can directly and type-safely use properties like this:
```java
import com.abc.Info;
. . .
@Value(Info.agent.username)
private String username;
```
This way the compiler directly validates `agent.username` and you can use Intellij for code completion, navigation into the properties file, usage searching, etc. Additionally, you can stop using Spring's `@PropertySource`, since Manifold handles properties files directly.
