### ISSUE TITLE
Template inheritance (extends) documentation is incorrect

### ISSUE THREAD

**Issue by shai-almog** [manifold-systems/manifold#448]
This page: https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-templates/README.md

Includes this example code:

```java

import model.Contact;
import manifold.templates.rt.runtime.BaseTemplate;

public class ExampleTemplate extends BaseTemplate {

  public String displayContact(Contact c) {
    if(c.hasName()) {
      return c.getName();
    } else {
      return c.getEmail();
    }
  }

}
```

Unfortunately `getTemplateResourceAsStream()` is abstract and missing from that sample. I wanted to fix the code but I'm a bit baffled about the default implementation. I looked [here](https://github.com/manifold-systems/manifold/blob/aa61fe37e96f844e44761a90fd7289e02a845a63/manifold-deps-parent/manifold-templates/src/main/java/manifold/templates/codegen/TemplateGen.java#L846), but that code seems to relate to compile time processing. Not to runtime which is where the template should be relevant.

**Comment by rsmckinney** [comment]
@shai-almog Hi.  Yep, looks like an error in the example. The class should be declared `abstract`. In fact, _all_ custom BaseTemplate subclasses should be declared abstract since the implementation for getTemplateResourceAsStream() is generated in the final class.

For instance, in the example ShowContact is generated and extends ExampleTemplate. Since getTemplateResourceAsStream() is abstract and generated in ShowContact, ExampleTemplate should be declared abstract. 

I'll correct the docs shortly. Apologies for the mix-up and thanks for reporting this!

**Comment by shai-almog** [comment]
That makes a lot of sense. Thanks!
