### ISSUE TITLE
[Bug] inconsistency between compiler and IntelliJ highlighting

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#482]
**Describe the bug**
When using `@get@set(Private) String privateSet` (or `@var @set(Private) String privateSet`) in a nested class and then create a subclass that is nested in the same root class as its parent, trying to assign a value to `privateSet` from the subclass will make IntelliJ show an error (see screenshot 2). 

When trying to run the code though, it runs without issue, due to methods from one nested class being accessible from another nested class, even when private.

**To Reproduce**
 - use code from screenshot 1
 - run the code

**Expected behavior**

**Screenshots**
Screenshot 1:
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/dcd89b3c-8ba0-4681-8422-e880a243b7a6)
Screenshot 2:
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/ed1003b0-b98f-48a7-814e-b8392da91274)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk-20.0.2
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.1.5
- Manifold version: 2023.1.18
- Manifold IntelliJ plugin version: 23.1.15

**Additional context**
Gist: https://gist.github.com/CC007/5f7e0c050eeb7978f53de55c131dd1c2

**Comment by rsmckinney** [comment]
Intellij is correctly reflecting standard Java rules wrt private access among nested Java classes. As you point out, manifold properties are slightly more tolerant here, but this is intentional.

The more lenient access within the source file enables properties to be more strict wrt access from other files, which in my view is a more pragmatic treatment compared with Java's. I may add a note about this in the documentation, but for the moment I'm comfortable with IntelliJ enforcing Java's rules and keeping this internal behavior as-is. At some point I may add a configuration tab in the IntelliJ settings plugin to enable manifold nested access rules vs. java's. _shrug_
