### ISSUE TITLE
Leave out then get/is prefix when working with method reference

### ISSUE THREAD

**Issue by ojecborec** [manifold-systems/manifold#499]
Hi,

Manifold has a nice feature when one can omit get/set prefix when working with Java beans. Suppose we have following Java bean

```java
public class Product {

    @var String name;

    public Product(String name) {
        this.name = name;
    }

}
```

I can read product name as `product.name` instead of `product.getName()`.

```java
var product = new Product("banana");
System.out.println(product.name);
```

I would like to leave out the `get` prefix even when reading product name as method reference.

```java
public class DemoApplication {

    public static void main(String[] args) {
        var products = List.of(
                new Product("apple"),
                new Product("banana")
        );

        products.stream()
                .map(Product::name)
                .forEach(System.out::println);
    }

}
```

This code fails with following message at the moment.

```
java: invalid method reference
  cannot find symbol
    symbol:   method name()
```

There's an easy fix to change the `map` method to `.map(Product::getName)` but it would be nice if we could write it as `.map(Product::name)` instead.

**Comment by rsmckinney** [comment]
Hi @ojecborec. Since properties are backed by getter/setter methods and since method refs are _method_ refs, there's not much that can be done, particularly because a method may have the same name as a property.

I suppose I could conjure up a special syntax for property refs, `Product::@name`?  But I'm content with the getter/setter method refs and lambdas. 

For me, method refs in stream code are awkward and require extra focus to grok. The marginal conciseness they offer is not worth the sacrifice in readability, again just my opinion:
```java
.map(Product::name) // I always pause an extra few seconds to grok this
```
vs.
```java
.map(p -> p.name) // this flows much better in my simple brain
```

Anyhow, I'm going to close this as: "Not a bad idea, but not worth the trouble."  But thanks for the suggestion!
