### ISSUE TITLE
IDEA Chinese Language Pack causes @var error

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#529]
![image](https://github.com/manifold-systems/manifold/assets/34852479/265ade83-93c6-49f9-858d-aadab015aefd)

Restore normal after uninstalling the plugin

**Comment by rsmckinney** [comment]
Ok, I see what is happening now.

The Manifold plugin suppresses some errors using the text of the error message (because there is no other way, no error message id is available). Since the Chinese pack translates all the error messages, error suppression fails to work.

But I see the Chinese pack plugin has over 24M downloads!  I'll get error suppression working with Chinese, one way or another.

**Comment by zcfire2017** [comment]
Thank you very much. Manifold is very powerful, really nb plus
