### ISSUE TITLE
[Feature] SQL: `fetchAll` instead of writing SQL query ourselves

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#547]
Currently, there are a few ways to select records from a database when using Manifold SQL, such as
* `Movie movie = "[.sql/] select * from movie where movie-id = :movieId".fetchOne(movieId);`
* `Movie movie = "[.sql/] select * from movie where movie-name = :movieName".fetchOne(movieName);`"
 
To make our lives a bit easier, there are methods that allows us to get records without writing SQL statements, such as:
* `Movie movie = Movie.fetch(movieId);`
* `Movie movie = Movie.fetchByName(movieName);`

But I'm missing another one: fetching all records of a specific type. Currenlty, I have to write:
*   `Iterable<Movie> movies ="[.sql/] select * from movie".fetch();`

But I would like to do it in the same way as the examples above, something like:
*  `Iterable<Movie> movies = Movie.fetchAll();` or `Iterable<Movie> movies = Movie.fetch();`

Is this possible to add? Or am I missing something, and is it already possible? (I'm still experimenting with Manifold SQL, so I might have overlooked something).

Thanks.

**Comment by rsmckinney** [comment]
Hi @EotT123. 

I considered it and passed because I thought it would make full table queries too inviting. But your expectations are probably right, I'll go ahead and include that in the API.

For now, if you want to experiment, it's easy to customize entity interfaces. To add a custom method to Movie you can either make a [custom interface](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-sql/readme.md#customizing-entity-types) or add an [extension method](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-classes-via-extension).

For manifold-sql it is usually best to make a custom interface. However, the manifold IntelliJ plugin does not yet support custom interfaces so you won't see code completion and there will be errors in the editor for call sites using your custom methods, but they will compile just fine. IDE support for this is coming soon. In this case another disadvantage is that since `fetchAll` would be a `static` interface method, you won't be able to call Movie.fetchAll() because Java static interface methods are not inherited, and since Movie is generated to extend your custom interface you'd have to call CustomMovie.fetchAll(), which kind of defeats the purpose of custom interfaces :/ So....

Another way to achieve this is with extension methods. This approach is supported in manifold's IntelliJ plugin and lets you call it as desired: Movie.fetchAll(). Here is the same thing for the `Film` table in the Sakila sample database.

![image](https://github.com/manifold-systems/manifold/assets/588843/d4b775bc-09c6-4567-89eb-255be5d5541d)

![image](https://github.com/manifold-systems/manifold/assets/588843/61f69328-e821-420a-9fc2-427b8a19b2da)

One more option is to simply put your query in a `.sql` resource file.
`AllMovies.sql`
```sql
select * from Film
```
Then just call `AllMovies.fetch()` wherever you need it. Easy-peasy.

But, yeah, I think I'll add `fetchAll()` methods to entities. Thanks for the suggestion.

**Comment by EotT123** [comment]
Thanks for your quick and extensive answer, @rsmckinney!

I was already wondering if you didn't support it for the reason you mentioned. That could indeed be a valid reason, but then again, it's always up to the developer to use the tools correctly and in a way that is optimal for the application. Not supporting it directly doesn't prevent the developer to do it anyway. 
I have a few usecases, where the tables are rather small (only a few tens of records), which I all need, so I need a `select *` anyway. So I'm happy to see that you are going to support it!

For now, I'll go either with the extension or the `AllMovies.sql` solution, as this seems to me the most easiest, without drawbacks, and trivial to switch later when it is natively supported.

**Comment by rsmckinney** [comment]
Feature available with release 2024.1.3

**Comment by EotT123** [comment]
That was really fast! Thanks!
