### ISSUE TITLE
Java > 8 support

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#58]
**Describe the bug**
When compiling with Java 10 or 11 (did not try 9, but assuming same issue), i receive the following error:
https://gist.github.com/aikar/14f04ec1633541149ee9aa60711c6ad0
Another dev on Windows received same issue

**To Reproduce**
1. JAVA_HOME="/usr/lib/jvm/11" mvn clean install -X

**Expected behavior**
Works

openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
- Manifold version: 0.55-alpha

**Comment by rsmckinney** [comment]
From the stack trace it looks like the Java 8 compiler is active... did you forget to remove the `tools.jar` maven profile in your pom?  Also, if you haven't already, checkout the docs for Maven setup [here](http://manifold.systems/docs.html#maven).

Let me know if you still have trouble.

**Comment by aikar** [comment]
sorry, I guess I should clarify - we're still targeting a java 8 output build, but used jdk11 to issue the compile.

If we bump to java11 target (is a near term goal) and then follow manifolds > 8 setup information, would that work?

Any way to support 11 to compile to 8 in mean time? i was mainly informed of this when one of my team mates was using java 10 to compile since everything on our stack until we added manifold worked fine under 10+.

**Comment by rsmckinney** [comment]
I see.  Yes, you can use manifold's java setup info for any kind of JDK version (8-12) options you have in mind.

Also if you are targeting Java 8, I would also recommend staying with JDK 8 in your build environment.  Otherwise there may be conflicts with tools.jar usage in JDK 8 vs. the jdk module in Java 9+.

Again let me know if you have build problems, I'd be happy to help you configure it to your preference.
