### ISSUE TITLE
IDE support for custom Manifolds

### ISSUE THREAD

**Issue by philippguertler** [manifold-systems/manifold#59]
Hello!

First of all: Great project, I love the idea.

I'm trying to create a custom manifold. For getting started I created a simple example based on the "Build Your Own Manifold" documentation. It creates a class with a single method.

```java
    public SrcClass make() {

        return new SrcClass(fqn, SrcClass.Kind.Class)
            .addMethod(new SrcMethod()
                .modifiers(Modifier.PUBLIC)
                .name("sayHello")
                .body(new SrcStatementBlock()
                    .addStatement(new SrcRawStatement()
                    .rawText("System.out.println(\"Hello!\");")))
                );
    }
```

I created a test which creates an object of that class and calls the sayHello method. It compiles and works as expected. However, IntelliJ does not recognize the class or the package and marks it as an error. Is there a way to get IntelliJ to find the generated package/class?

**Comment by rsmckinney** [comment]
Hi @philippguertler.   Thanks!

Does the project you are using in IJ have a dependency on your custom manifold classes/Jar?  For instance, if the project is defined with maven or gradle, you need to add a dependency to your custom manifold using normal maven or gradle dependency syntax.  Otherwise, if your project is managed by IJ, you have to add a dependency to your custom manifold that way.

If you still have trouble, I'd be happy assist (make a github project I can access, send it over email, etc.).

Cheers.

**Comment by philippguertler** [comment]
I have a single project using maven. Do I have to add anything to the pom.xml in order for the IDE to find the generated classes?

I have uploaded my code to this repo: https://github.com/philippguertler/mesh-manifold

My plan for later is to generate POJOs out of the `src/test/resources/mesh/schemas.json` file.

**Comment by rsmckinney** [comment]
Ah.  Do you mean to use the Manifold IJ plugin on your mesh-manifold _test_ classes?  If so, you must define a separate test module, otherwise your mesh-manifold module is in a chicken/egg scenario -- IJ can't use it to build itself.  You can use the Manifold [project structure](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent) as a model.

I built a small sample project to use your mesh-manifold as dependency using the following pom file.  The Manifold IJ plugin attempts to resolve against your mesh-manifold, but you have some bugs to fix :-)  Let me know if you need help.  I just opened a new [Manifold gitter.im](https://gitter.im/manifold-systems/community) for such discussions.  Feel free to start one, or if you are more comfortable with github issues, this is fine too.

**mesh-manifold sample pom.xml**
```maven
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gentics</groupId>
    <artifactId>mesh-sample</artifactId>
    <version>1.0-SNAPSHOT</version>


    <properties>
        <manifold-version>0.58-alpha</manifold-version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.gentics</groupId>
            <artifactId>mesh-manifold</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!--Adding Manifold Extensions-->
        <dependency>
            <groupId>systems.manifold</groupId>
            <artifactId>manifold-ext</artifactId>
            <version>${manifold-version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!--
      Add tools.jar from the jdk (exclusively for Java 8 usage)
    -->
    <profiles>
        <profile>
            <id>internal.tools-jar</id>
            <activation>
                <file>
                    <exists>${java.home}/../lib/tools.jar</exists>
                </file>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.sun</groupId>
                    <artifactId>tools</artifactId>
                    <version>1.8.0</version>
                    <scope>system</scope>
                    <systemPath>${java.home}/../lib/tools.jar</systemPath>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <build>
        <plugins>

            <!--
             *** JAVA 8 ***

             Configure the maven-compiler-plugin use Manifold.
             - add the -Xplugin:Manifold argument for the javac compiler
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>

                        <!--Add the Manifold plugin, with string templates enabled-->
                        <arg>-Xplugin:Manifold strings exceptions</arg>

                    </compilerArgs>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
```

**Comment by philippguertler** [comment]
Thank you for your help. Please take a look at https://github.com/philippguertler/mesh-manifold again. I have restructured the project as you suggested. However the result is still the same.
Here is how it looks for me:

![mesh-manifold](https://user-images.githubusercontent.com/13328856/55670514-9d08b900-5885-11e9-900f-8830b0b425bf.png)

As you can see the test works fine and I can even see the generated class in the project tree. However, IntelliJ refuses to find the class in the editor.

**Comment by rsmckinney** [comment]
It is difficult to make the IntelliJ plugin recognize a type manifold in the same project in which it is defined. You can definitely develop and test it, as you already have done, but using the type manifold in the plugin while developing the type manifold is tricky. Considering a type manifold isn't useful in the IJ plugin until it's working well, it mostly doesn't make much sense to develop with it enabled.  But I fully understand the expectation.

In any case you *can* make this work with some changes to how you declare the dependency on the type manifold.  Essentially, the dependency must be a packaged JAR file, not a class directory -- this is a limitation of Java's service manager.  You can configure `<system>` in your dependency to make that work.  I've provided a patch file for your project with this already setup, if you'd like to try it [[here]](https://dl.dropbox.com/s/gwa064jzuj0gqyf/patch.patch).  Note since your type mesh manifold works with JSON files, I modified the dependencies to use manifold-ext instead of manifold-all to remove any change of conflict with Manifold's provided JSON type manifold.

I would recommend *not* developing with this configuration, however, because it doesn't take much for a buggy type manifold to destabilize IJ -- you'll end up restarting a lot etc.  It's much better to build and test the type manifold separate from testing it with the plugin.

Also, it's worth noting the Manifold IJ plugin does not use any generated artifacts from a type manifold, like class files etc.  This is because the IJ plugin must work exclusively with source/resource files in your project e.g., make a change in a JSON file and use the change immediately in your Java source without compiling.  As such the IJ plugin has it's own way of dynamically driving type manifolds separate from the build step.

**Comment by philippguertler** [comment]
Thank you very much. It works now when I use `mvn install` and only use the jar in the test project.
