### ISSUE TITLE
manifold-strings: `this.` missing syntax highlighting & references in string templates

### ISSUE THREAD

**Issue by s809** [manifold-systems/manifold#624]
When class members in string templates are prefixed with `this`, they have no syntax highlighting and they don't show up in references.

Works:
![image](https://github.com/user-attachments/assets/ff02bc9c-05ae-4579-b534-e88aa0a54bef)
![image](https://github.com/user-attachments/assets/93e097d0-9b03-4476-a742-d478ba92feac)

Does not work:
![image](https://github.com/user-attachments/assets/1c1ea96d-3a2d-458b-aed5-741ed46c8aa8)

**Comment by rsmckinney** [comment]
The manifold plugin integrates Java expressions in string templates using IntelliJ's language injection feature. In order to parse correctly, the injection API requires that expressions are wrapped in a class. Using your failed example, the expression is parsed something like this:
```java
class Xxx { Object xxxfield = this.serverLevelWrapper.getDimensionName(); }
```  
The problem appears to be that `this` is a reference to class `Xxx`, being a _local_ inner class `this` does not have access to the outer `serverLevelWrapper` field. I would chalk this up as a general limitation of language injection. Or, perhaps there is another way to expose the expressions in a way where `this` works as expected?

**Comment by s809** [comment]
I don't know much about IntelliJ's plugin system yet, but is there a way to at least somewhat transparently "rewrite" `this` into `ClassName.this` in that case?

**Comment by rsmckinney** [comment]
Latest plugin now supports the simple case where an expression begins with `this`.
