### ISSUE TITLE
Difficulties using manifold in Android Studio

### ISSUE THREAD

**Issue by Schommer475** [manifold-systems/manifold#628]
I am using Android Studio on Ubuntu. I have the manifold plugin installed and my current goal is to get a sort of 'hello world' going before doing some experiments to test out how some of manifold's features work. To that end, I have created an empty Android Studio project and created a library module for the experiments within it. The class I am trying to extend at the moment is java.lang.String.

For good measure, I have included the dependencies in both the app and module build.gradle files. Gradle sync works just find but Gradle build fails on both, with completely different messages.

I could really use some help figuring out what I am doing wrong.

Here is the module build.gradle file:

    plugins {
        alias(libs.plugins.android.library)
    }
  
    getTasks().withType(JavaCompile) {
        options.compilerArgs += ['-Xplugin:Manifold']
    }
  
    android {
        namespace 'com.components.manifoldexperiments'
        compileSdk 34
  
        defaultConfig {
            minSdk 33
  
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            consumerProguardFiles "consumer-rules.pro"
        }
  
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
        }
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
        }
    }
  
    dependencies {
  
        implementation libs.appcompat
        implementation libs.material
        testImplementation libs.junit
        androidTestImplementation libs.ext.junit
        androidTestImplementation libs.espresso.core
        compileOnly 'systems.manifold:manifold:2024.1.36'
        implementation 'systems.manifold:manifold-rt:2024.1.36'
        compileOnly 'systems.manifold:manifold-ext:2024.1.36'
        implementation 'systems.manifold:manifold-ext-rt:2024.1.36'
        annotationProcessor group: 'systems.manifold', name: 'manifold-ext', version: '2024.1.36'
        testAnnotationProcessor group: 'systems.manifold', name: 'manifold-ext', version: '2024.1.36'
    }

  And the console dump:

  Executing tasks: [:ManifoldExperiments:assembleDebug, :ManifoldExperiments:assembleDebugUnitTest, :ManifoldExperiments:assembleDebugAndroidTest] in project /home/tim/AndroidStudioProjects/ManifoldExperiments

  > Task :ManifoldExperiments:preBuild UP-TO-DATE
  > Task :ManifoldExperiments:preDebugBuild UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugJniLibFolders UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugNativeLibs NO-SOURCE
  > Task :ManifoldExperiments:stripDebugDebugSymbols NO-SOURCE
  > Task :ManifoldExperiments:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugResValues UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugResources UP-TO-DATE
  > Task :ManifoldExperiments:packageDebugResources UP-TO-DATE
  > Task :ManifoldExperiments:parseDebugLocalResources UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugRFile UP-TO-DATE
  > Task :ManifoldExperiments:extractDebugAnnotations UP-TO-DATE
  > Task :ManifoldExperiments:extractDeepLinksForAarDebug UP-TO-DATE
  > Task :ManifoldExperiments:javaPreCompileDebug UP-TO-DATE
  
  > Task :ManifoldExperiments:compileDebugJavaWithJavac FAILED
  java/lang/String.java:5: error: package java.lang.constant does not exist
  public final class String extends java.lang.Object implements java.io.Serializable, java.lang.Comparable<java.lang.String>, java.lang.CharSequence, java.lang.constant.Constable, java.lang.constant.ConstantDesc {
                                                                                                                                                                      ^
  java/lang/String.java:5: error: package java.lang.constant does not exist
  public final class String extends java.lang.Object implements java.io.Serializable, java.lang.Comparable<java.lang.String>, java.lang.CharSequence, java.lang.constant.Constable, java.lang.constant.ConstantDesc {
                                                                                                                                                                                                    ^
  java/lang/String.java:216: error: cannot find symbol
    private boolean nonSyncContentEquals(java.lang.AbstractStringBuilder arg0) {
                                                  ^
    symbol:   class AbstractStringBuilder
    location: package java.lang
  java/lang/String.java:445: error: cannot find symbol
    String(java.lang.AbstractStringBuilder arg0, java.lang.Void arg1) {
                    ^
    symbol:   class AbstractStringBuilder
    location: package java.lang
  java/lang/Object.java:6: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                               ^
  java/lang/Object.java:10: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                             ^
  java/lang/Object.java:14: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                               ^
  java/lang/Object.java:21: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                               ^
  java/lang/Object.java:28: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                             ^
  java/lang/Object.java:32: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                               ^
  java/lang/String.java:20: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.IntrinsicCandidate()
                             ^
  java/lang/String.java:318: error: package jdk.internal.vm.annotation does not exist
    @jdk.internal.vm.annotation.ForceInline()
                               ^
  12 errors

  > Task :ManifoldExperiments:mergeDebugShaders UP-TO-DATE
  > Task :ManifoldExperiments:compileDebugShaders NO-SOURCE
  > Task :ManifoldExperiments:generateDebugAssets UP-TO-DATE
  > Task :ManifoldExperiments:packageDebugAssets UP-TO-DATE
  > Task :ManifoldExperiments:prepareDebugArtProfile UP-TO-DATE
  > Task :ManifoldExperiments:prepareLintJarForPublish UP-TO-DATE
  > Task :ManifoldExperiments:processDebugManifest UP-TO-DATE
  > Task :ManifoldExperiments:writeDebugAarMetadata UP-TO-DATE
  > Task :ManifoldExperiments:preDebugUnitTestBuild UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugUnitTestStubRFile UP-TO-DATE
  > Task :ManifoldExperiments:javaPreCompileDebugUnitTest UP-TO-DATE
  > Task :ManifoldExperiments:preDebugAndroidTestBuild UP-TO-DATE
  > Task :ManifoldExperiments:javaPreCompileDebugAndroidTest UP-TO-DATE
  > Task :ManifoldExperiments:checkDebugAndroidTestAarMetadata UP-TO-DATE
  > Task :ManifoldExperiments:compileDebugLibraryResources UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugAndroidTestResValues UP-TO-DATE
  > Task :ManifoldExperiments:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
  > Task :ManifoldExperiments:generateDebugAndroidTestResources UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugAndroidTestResources UP-TO-DATE
  > Task :ManifoldExperiments:extractDeepLinksDebug UP-TO-DATE
  > Task :ManifoldExperiments:processDebugAndroidTestManifest UP-TO-DATE
  > Task :ManifoldExperiments:processDebugAndroidTestResources UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugAndroidTestShaders UP-TO-DATE
  > Task :ManifoldExperiments:compileDebugAndroidTestShaders NO-SOURCE
  > Task :ManifoldExperiments:generateDebugAndroidTestAssets UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugAndroidTestAssets UP-TO-DATE
  > Task :ManifoldExperiments:compressDebugAndroidTestAssets UP-TO-DATE
  > Task :ManifoldExperiments:desugarDebugAndroidTestFileDependencies UP-TO-DATE
  > Task :ManifoldExperiments:processDebugAndroidTestJavaRes NO-SOURCE
  > Task :ManifoldExperiments:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
  > Task :ManifoldExperiments:mergeExtDexDebugAndroidTest UP-TO-DATE
  > Task :ManifoldExperiments:copyDebugJniLibsProjectOnly UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
  > Task :ManifoldExperiments:mergeDebugAndroidTestNativeLibs NO-SOURCE
  > Task :ManifoldExperiments:stripDebugAndroidTestDebugSymbols NO-SOURCE
  > Task :ManifoldExperiments:validateSigningDebugAndroidTest UP-TO-DATE
  > Task :ManifoldExperiments:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE

  FAILURE: Build failed with an exception.

  * What went wrong:
  Execution failed for task ':ManifoldExperiments:compileDebugJavaWithJavac'.
  > Compilation failed; see the compiler error output for details.

  * Try:
  > Run with --info option to get more log output.
  > Run with --scan to get full insights.

  BUILD FAILED in 919ms
  39 actionable tasks: 1 executed, 38 up-to-date

And here is the app build.gradle:

    plugins {
        alias(libs.plugins.android.application)
    }

    android {
        namespace 'com.components.manifoldexperiments'
        compileSdk 34

      defaultConfig {
          applicationId "com.components.manifoldexperiments"
          minSdk 33
          targetSdk 34
          versionCode 1
          versionName "1.0"

          testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
      }

      buildTypes {
          release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
          }
      }
      compileOptions {
          sourceCompatibility JavaVersion.VERSION_17
          targetCompatibility JavaVersion.VERSION_17
      }
    }

    dependencies {

      implementation libs.appcompat
      implementation libs.material
      testImplementation libs.junit
      androidTestImplementation libs.ext.junit
      androidTestImplementation libs.espresso.core
      compileOnly 'systems.manifold:manifold:2024.1.36'
      implementation 'systems.manifold:manifold-rt:2024.1.36'
      compileOnly 'systems.manifold:manifold-ext:2024.1.36'
      implementation 'systems.manifold:manifold-ext-rt:2024.1.36'
      annotationProcessor group: 'systems.manifold', name: 'manifold-ext', version: '2024.1.36'
      testAnnotationProcessor group: 'systems.manifold', name: 'manifold-ext', version: '2024.1.36'
    }

    tasks.withType(JavaCompile) {
        options.compilerArgs += ['-Xplugin:Manifold']
    }

And the console dump:

  plug-in not found: Manifold

**Comment by rsmckinney** [comment]
Based on the compile errors it appears you may be compiling with an older JDK. For instance:
```
java/lang/String.java:5: error: package java.lang.constant does not exist
```
The `java.lang.constant` package is available beginning with JDK 17. The only way that error can surface, I would think, is if your build is targeting or using a JDK prior to 17. This type of error may result from:
- using the wrong version of Gradle 
- using the wrong JDK to run Gradle
- if compiling with IntelliJ, not setting the Project JDK in Settings appropriately

Regarding build config, depending on the target API / SDK etc. Android can be touchy. Typically, you don't want to apply the same dependency as both `compileOnly` and `annotationProcessor`, normally use one or the other. And, again for some reason depending on build config with Android, sometimes `compileOnly` works, others `annotationProcessor` works. If Android behaved properly, `annotationProcessor` should always work. Shrug.

Also, since `manifold-ext` brings in `manifold`, you should be able to eliminate the `manifold` & `manifold-rt` dependencies.

Perhaps try:

```groovy
. . .
  implementation 'systems.manifold:manifold-ext-rt:2024.1.36'
  compileOnly 'systems.manifold:manifold-ext:2024.1.36'
```

or:

```groovy
. . .
  implementation 'systems.manifold:manifold-ext-rt:2024.1.36'
  annotationProcessor 'systems.manifold:manifold-ext:2024.1.36'
```

Hope this helps.

**Comment by Schommer475** [comment]
I still can't get it working.

Gradle version: 8.9
Android gradle plugin version: 8.5.0
JDK used to run gradle: Jetbrains Runtime 17.0.10
source and target compile compatibility: JavaVersion.VERSION_17
java version used to compile: 17

My current thought is that maybe the jetbrains runtime doesn't expose the same set of annotations, though I have been unable to confirm and that likely wouldn't account for the String errors.

I have also tried both of your suggestions regarding dependencies. No difference.

**Comment by rsmckinney** [comment]
This issue appears to be with the internals of the android build configuration. For instance, the errors corresponding with your benign String extension class such as the `java.lang.constant` package being undefined appear to be baked into the android build environment. The errors all involve mostly internal JDK implementation details that don't normally surface in Java app code. I suspect these packages/classes aren't supported in the android runtime. Indeed, if you try to use any of the packages directly in any app code, they are not supported. Consequently, there is nothing about this that is specific to what manifold is doing during compilation.

Unfortunately, manifold tests don't exercise most of the libraries in an android environment. Because the manifold subprojects, including `manifold-ext`, are thoroughly tested in the Java SE environment, only periphery android specific stuff is tested separately. And that stuff is currently mostly tested in Java 8, which sheds light on a (at least an interim) solution to the problem.

The `java.lang.constant` package and all the other packages and classes that cause errors with the String extension are all relatively new, they are post JDK 11. Again, I suspect the subset of android-supported JDK excludes these for various reasons. But that means if you build with JDK 11 source/target compatibility, those unsupported classes won't be included in manifold's projection of extended JDK classes, such as String.  Yeah, this is not an ideal solution; you can't use JDK 17-specific features in the modules where you define extension classes. It does appear to work though.

So I would suggest, for now, if you are going to build extension classes for JDK classes, like your String example, you should make a separate module for those and specify JDK 11 source/target. Or, perhaps better, just build a separate project for your JDK extensions using your preferred JDK (17 in this case) and then use that project as a dependency.

Here is a simple build.gradle similar to your example that uses JDK 11 source/target. Note, it also uses a JDK 11 toolchain. Note, the gradle JDK is still 17 as is JAVA_HOME on the command line.

```groovy
plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.testandroid'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.testandroid"
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(11)
        }
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation 'systems.manifold:manifold-ext-rt:2024.1.37-SNAPSHOT'
    annotationProcessor 'systems.manifold:manifold-ext:2024.1.37-SNAPSHOT'
    testImplementation 'systems.manifold:manifold-ext-rt:2024.1.37-SNAPSHOT'
    testAnnotationProcessor 'systems.manifold:manifold-ext:2024.1.37-SNAPSHOT'
    androidTestImplementation 'systems.manifold:manifold-ext-rt:2024.1.37-SNAPSHOT'
    androidTestAnnotationProcessor 'systems.manifold:manifold-ext:2024.1.37-SNAPSHOT'
}

getTasks().withType(JavaCompile) {
    options.compilerArgs += ['-Xplugin:Manifold']
}
```

Apologies for the confusion. As I recall this issue or similar issues have come up in the past each time being waved away by the submitters because they "got it working", my fault for not digging in to understand.  I suspect most android devs using manifold-ext aren't creating extension classes on JDK classes, that or they aren't using JDK 17+.  _shrug_

**Comment by Schommer475** [comment]
Thanks for the help, I think we are getting closer. I had to install a jdk 11 compiler, but once I did, this was the compile error message:

Could not find systems.manifold:manifold-ext-rt:2024.1.37-SNAPSHOT

If that is a recent patch, has it been published?

Funny you should mention most developers not extending JDK classes. I wasn't initially either. I had created a base class in a neighboring package to test with. I got the errors about "package jdk.internal.vm.annotation does not exist
@jdk.internal.vm.annotation.IntrinsicCandidate()" and I tried using String instead as a way of getting it going.

Ultimately, once I am more confident with what I can and can't do with Manifold, my hope is to shim some behaviors onto the View base class that I feel should have been there from the onset.

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.38.  Also a fix in android studio plugin release 2024.1.13, updatable in android studio by EOD today.

Please note, source compatibility version and JDK version must match with android when using manifold-ext. In your case, since you are using android 34 API, this means you must change android gradle settings to use JDK **17**, also on command line set JAVA_HOME to JDK **17**.

**Comment by Schommer475** [comment]
That fixed it. Thank you.

**Comment by rsmckinney** [comment]
Note, see #639.  You can now use a newer JDK to compile android apps when targeting an older JDK e.g., use JDK 21 to compile an app targeting JDK 17.
