### ISSUE TITLE
Manifold From A "Type Service" Instead Of Local Resources?

### ISSUE THREAD

**Issue by monomasmalo** [manifold-systems/manifold#98]
I've only recently discovered Manifold and have just started testing with some of the demos, but it looks like a promising solution for several projects i'm working on. Thanks for sharing it with the community.

One enhancement/capability that would be extremely valuable for my use cases is the ability to consume type definitions from a service rather than from the project's resources folder. For example, imagine an environment where type definitions (JSON schemas, SCIM 2, Avro) are managed centrally by a few services that are in turn consumed by dozens of (micro)services for a range of specific use cases. Would it be possible/advisable to configure a Manifold to consume from one or more services directly, live over the network, during development, with feature parity with local-resource-based Manifolds? Is that something that others would consider a value add to the project?

It looks like this use case _may_ already be under consideration via the `UrlTypeManifold` abstract class, but it doesn't appear to have any concrete implementations yet.

If such a feature is possible/advisable, I'm willing to contribute time/code/testing, but i'd appreciate guidance as to how best to help.

Thanks in advance.

**Comment by rsmckinney** [comment]
Hi @monomasmalo.  The `ITypeManifold` API is intentionally open to accommodate any kind of protocol including URLs.  Lots of potential applying manifold to network type domains and databases like RDF, World Bank, etc.  But the dynamic nature of a "networked" manifold may be unsuited for some projects mostly because:
* it requires network access to build a project
* presumably it's accessed via URL because it changes, which is counter to a versioned dependency
* it's not managed in source control

I don't think URLs and Files are necessarily an either/or proposition, however.  As it happens, I'm considering adding an "subscription" API so that a type manifold can declare a provider of metadata so that IDE tooling can interface with the user to periodically update it.  This would work well for URL-based schemas.

All that said, there is nothing wrong with building a purely networked manifold.  I can imagine some interesting projects using that concept.  As I recall the F# type provider API was built around that idea.  What did you have in mind?

**Comment by rsmckinney** [comment]
Hi @monomasmalo.  Any progress on service oriented manifolds?  Any other questions?
